[project]
name = "tools"
version = "0.1.1"
description = "helpers and set up scripts for yarkie"
requires-python = ">=3.11"
dependencies = [
    "click == 8.1.7",
    "pandas == 2.1.3",
    "pydantic == 2.4.2",
    "requests == 2.31.0",
    "scikit-learn == 1.3.2",
    "sqlite-utils == 3.35.1",
    "yt-dlp == 2023.10.13",
]

[project.scripts]
tools = "cli:cli"

[project.optional-dependencies]
test = [
  "faker == 20.1.0",
  "polyfactory == 2.12.0",
  "pytest == 7.4.3",
  "pytest-cov == 4.1.0"
]
